# Generated by Django 4.2.6 on 2023-11-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('rol', models.TextField(default='Elige tu rol en la página', max_length=8, verbose_name='rol')),
                ('nivel', models.TextField(choices=[('Elige un nivel educativo', 'Elige un nivel educativo'), ('Básica', 'Básica'), ('Media', 'Media'), ('Universitaria', 'Universitaria')], default='Elige un nivel educativo')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('materia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Materia')),
                ('horario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Horario de Atención')),
                ('precio', models.IntegerField(blank=True, null=True, verbose_name='Precio')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
